const dummyJobs = [
  {
    id: 1,
    title: "Software Engineer",
    image: `https://rb.gy/noflfw`,
    company: "Tech Co.",
    location: "San Francisco, CA",
    status: "Remote",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    experience: "2-3 years",
    role: "Development",
    days: 5,
    salary: 15
  },
  {
    id: 2,
    title: "Data Analyst",
    company: "Data Corp.",
    image: `https://rb.gy/noflfw`,
    location: "New York, NY",
    status: "On-site",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    experience: "2-3 years",
    role: "Development",
    days: 4,
    salary: 45
  },
  {
    id: 3,
    title: "Marketing Manager",
    company: "Marketing Solutions",
    image: `https://rb.gy/noflfw`,
    location: "Los Angeles, CA",
    status: "Hybrid",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    experience: "3+ years",
    role: "Marketing",
    days: 3,
    salary: 30
  },
  {
    id: 4,
    title: "Product Designer",
    company: "Design Studio",
    image: `https://rb.gy/noflfw`,
    location: "Seattle, WA",
    status: "Remote",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    experience: "4+ years",
    role: "Marketing",
    days: 6,
    salary: 20
  },
  {
    id: 5,
    title: "Financial Analyst",
    company: "Finance Inc.",
    image: `https://rb.gy/noflfw`,
    location: "Chicago, IL",
    status: "On-site",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    experience: "2+ years",
    role: "Finance",
    days: 3,
    salary: 15
  },
  {
    id: 6,
    title: "Data Scientist",
    company: "Data Insights Co.",
    image: "https://rb.gy/noflfw",
    location: "Boston, MA",
    status: "Remote",
    description: "Join our team of data scientists to conduct advanced analytics and build predictive models for business insights.",
    experience: "3-5 years",
    role: "Data Science",
    days: 5,
    salary: 55
  },
  {
    id: 7,
    title: "Software Developer",
    company: "Software Solutions Ltd.",
    image: "https://rb.gy/noflfw",
    location: "Austin, TX",
    status: "On-site",
    description: "We're seeking a skilled software developer to contribute to the development of innovative software solutions.",
    experience: "2-4 years",
    role: "Development",
    days: 6,
    salary: 40
  },
  {
    id: 8,
    title: "Business Analyst",
    company: "Business Insights Inc.",
    image: "https://rb.gy/noflfw",
    location: "Washington, D.C.",
    status: "Hybrid",
    description: "Analyze business processes and provide actionable insights to drive organizational growth and efficiency.",
    experience: "3+ years",
    role: "Business Analysis",
    days: 7,
    salary: 35
  },
  {
    id: 9,
    title: "UX/UI Designer",
    company: "Creative Designs Co.",
    image: "https://rb.gy/noflfw",
    location: "Denver, CO",
    status: "Remote",
    description: "Design user-centric interfaces and experiences for web and mobile applications.",
    experience: "2-3 years",
    role: "Design",
    days: 6,
    salary: 25
  },
  {
    id: 10,
    title: "HR Manager",
    company: "HR Solutions Ltd.",
    image: "https://rb.gy/noflfw",
    location: "New York, NY",
    status: "On-site",
    description: "Manage human resources activities including recruitment, employee relations, and performance management.",
    experience: "5+ years",
    role: "Human Resources",
    days: 9,
    salary: 50
  },
  {
    id: 11,
    title: "Data Engineer",
    company: "DataWorks Inc.",
    image: "https://rb.gy/noflfw",
    location: "Seattle, WA",
    status: "Remote",
    description: "Develop and maintain scalable data pipelines to support data analytics and machine learning applications.",
    experience: "3-5 years",
    role: "Data Engineering",
    days:9,
    salary: 60
  },
  {
    id: 12,
    title: "Cybersecurity Analyst",
    company: "CyberDefend Solutions",
    image: "https://rb.gy/noflfw",
    location: "Dallas, TX",
    status: "On-site",
    description: "Analyze security threats and vulnerabilities to protect against cyber attacks and ensure data confidentiality.",
    experience: "2-4 years",
    role: "Cybersecurity",
    days: 7,
    salary: 70
  },
  {
    id: 13,
    title: "Operations Analyst",
    company: "Operational Insights Co.",
    image: "https://rb.gy/noflfw",
    location: "Miami, FL",
    status: "Hybrid",
    description: "Optimize operational processes and workflows through data analysis and performance monitoring.",
    experience: "3-5 years",
    role: "Operations",
    days: 3,
    salary: 55
  },
  {
    id: 14,
    title: "Quantitative Analyst",
    company: "Quantitative Analytics Inc.",
    image: "https://rb.gy/noflfw",
    location: "New York, NY",
    status: "Remote",
    description: "Develop quantitative models and algorithms for financial trading and risk management.",
    experience: "4-6 years",
    role: "Quantitative Analysis",
    days: 7,
    salary: 85
  },
  {
    id: 15,
    title: "Healthcare Data Analyst",
    company: "HealthTech Analytics",
    image: "https://rb.gy/noflfw",
    location: "San Francisco, CA",
    status: "On-site",
    description: "Analyze healthcare data to improve patient outcomes, reduce costs, and optimize healthcare delivery.",
    experience: "3-5 years",
    role: "Healthcare Analytics",
    days: 5,
    salary: 75
  },
  {
    id: 16,
    title: "Supply Chain Analyst",
    company: "SupplyChain Solutions",
    image: "https://rb.gy/noflfw",
    location: "Chicago, IL",
    status: "Remote",
    description: "Analyze supply chain data to optimize inventory management, logistics, and distribution.",
    experience: "2-4 years",
    role: "Supply Chain",
    days: 8,
    salary: 65
  },
  {
    id: 17,
    title: "Business Intelligence Analyst",
    company: "BI Insights Group",
    image: "https://rb.gy/noflfw",
    location: "Boston, MA",
    status: "On-site",
    description: "Design and develop business intelligence solutions to enable data-driven decision-making.",
    experience: "3-5 years",
    role: "Business Intelligence",
    days: 4,
    salary: 80
  },
  {
    id: 18,
    title: "Research Analyst",
    company: "Research Insights Co.",
    image: "https://rb.gy/noflfw",
    location: "Washington, D.C.",
    status: "Hybrid",
    description: "Conduct qualitative and quantitative research to support strategic decision-making and business planning.",
    experience: "2-4 years",
    role: "Research",
    days: 6,
    salary: 70
  },
  {
    id: 19,
    title: "Sales Operations Analyst",
    company: "SalesTech Solutions",
    image: "https://rb.gy/noflfw",
    location: "Los Angeles, CA",
    status: "On-site",
    description: "Analyze sales data and processes to optimize sales performance and drive revenue growth.",
    experience: "3-5 years",
    role: "Sales Operations",
    days: 3,
    salary: 75
  },
  {
    id: 20,
    title: "Data Governance Analyst",
    company: "DataGuard Solutions",
    image: "https://rb.gy/noflfw",
    location: "San Diego, CA",
    status: "Remote",
    description: "Implement data governance frameworks and policies to ensure data quality, integrity, and compliance.",
    experience: "4-6 years",
    role: "Data Governance",
    days: 5,
    salary: 85
  },
  {
    id: 21,
    title: "Customer Insights Analyst",
    company: "Customer Analytics Co.",
    image: "https://rb.gy/noflfw",
    location: "Atlanta, GA",
    status: "On-site",
    description: "Analyze customer data to identify trends, preferences, and behaviors to enhance customer experience and retention.",
    experience: "2-3 years",
    role: "Customer Insights",
    days: 7,
    salary: 60
  },
  {
    id: 22,
    title: "Environmental Data Analyst",
    company: "EcoTech Analytics",
    image: "https://rb.gy/noflfw",
    location: "Portland, OR",
    status: "Remote",
    description: "Analyze environmental data to support environmental research, conservation efforts, and sustainability initiatives.",
    experience: "3-5 years",
    role: "Environmental Analytics",
    days: 5,
    salary: 70
  },
  {
    id: 23,
    title: "Quality Assurance Analyst",
    company: "QualityTech Solutions",
    image: "https://rb.gy/noflfw",
    location: "Houston, TX",
    status: "On-site",
    description: "Develop and execute test plans to ensure the quality, reliability, and performance of software applications.",
    experience: "2-4 years",
    role: "Quality Assurance",
    days: 8,
    salary: 55
  },
  {
    id: 24,
    title: "Risk Analyst",
    company: "Risk Management Co.",
    image: "https://rb.gy/noflfw",
    location: "Miami, FL",
    status: "Remote",
    description: "Identify, assess, and mitigate risks through data analysis and risk modeling.",
    experience: "3-5 years",
    role: "Risk Analysis",
    days: 5,
    salary: 75
  },
  {
    id: 25,
    title: "Data Governance Specialist",
    company: "DataCare Solutions",
    image: "https://rb.gy/noflfw",
    location: "Dallas, TX",
    status: "On-site",
    description: "Lead the implementation and management of data governance frameworks and policies.",
    experience: "4-6 years",
    role: "Data Governance",
    days: 4,
    salary: 80
  },
  {
    id: 26,
    title: "IT Business Analyst",
    company: "IT Solutions Inc.",
    image: "https://rb.gy/noflfw",
    location: "Chicago, IL",
    status: "Remote",
    description: "Bridge the gap between IT and business stakeholders by analyzing business requirements and translating them into technical solutions.",
    experience: "3-5 years",
    role: "IT Business Analysis",
    days: 8,
    salary: 70
  },
  {
    id: 27,
    title: "Customer Support Analyst",
    company: "Support Solutions Co.",
    image: "https://rb.gy/noflfw",
    location: "New York, NY",
    status: "On-site",
    description: "Analyze customer support data to identify trends and opportunities for improving customer satisfaction and service quality.",
    experience: "2-4 years",
    role: "Customer Support",
    days: 6,
    salary: 55
  },
  {
    id: 28,
    title: "Statistical Analyst",
    company: "Statistics Insights Co.",
    image: "https://rb.gy/noflfw",
    location: "Los Angeles, CA",
    status: "Remote",
    description: "Perform statistical analysis and modeling to support research projects, business decisions, and policy development.",
    experience: "3-5 years",
    role: "Statistical Analysis",
    days: 5,
    salary: 75
  },
  {
    id: 29,
    title: "Database Analyst",
    company: "Database Solutions Ltd.",
    image: "https://rb.gy/noflfw",
    location: "Seattle, WA",
    status: "On-site",
    description: "Design and maintain database systems to support data storage, retrieval, and analysis.",
    experience: "2-4 years",
    role: "Database Administration",
    days: 4,
    salary: 65
  },
  {
    id: 30,
    title: "Research Data Analyst",
    company: "Research Insights Co.",
    image: "https://rb.gy/noflfw",
    location: "Washington, D.C.",
    status: "Hybrid",
    description: "Collect, clean, and analyze research data to support academic research projects and publications.",
    experience: "2-4 years",
    role: "Research Analysis",
    days: 6,
    salary: 70
  }

];

export default dummyJobs;